WITH RECORDS AS (
    SELECT O.ANIMAL_ID, O.NAME, I.DATETIME AS IN_DATE, O.DATETIME AS OUT_DATE
    FROM ANIMAL_OUTS O LEFT JOIN ANIMAL_INS I
    ON O.ANIMAL_ID = I.ANIMAL_ID
)

SELECT ANIMAL_ID, NAME
FROM RECORDS
WHERE IN_DATE IS NULL
ORDER BY ANIMAL_ID