WITH RECORDS AS (
    SELECT T.FLAVOR, SUM(T.TOTAL_ORDER) AS SUMMATION
    FROM (
        SELECT FLAVOR, TOTAL_ORDER FROM FIRST_HALF FH
        UNION ALL
        SELECT FLAVOR, TOTAL_ORDER FROM JULY J
    ) T
    GROUP BY T.FLAVOR
    ORDER BY SUMMATION DESC
)

SELECT FLAVOR
FROM RECORDS
LIMIT 3