WITH TOTAL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOT
    FROM (
        SELECT * FROM FIRST_HALF
        UNION ALL
        SELECT * FROM JULY
    ) AS U
    GROUP BY FLAVOR
    ORDER BY TOT DESC
)

SELECT FLAVOR FROM TOTAL LIMIT 3;