-- 코드를 입력하세요
WITH RECURSIVE FULL_HOURS AS (
SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM FULL_HOURS WHERE HOUR<23
)
SELECT FH.HOUR, COUNT(A.ANIMAL_ID) AS 'COUNT'
FROM FULL_HOURS AS FH
LEFT JOIN ANIMAL_OUTS AS A ON FH.HOUR = HOUR(A.DATETIME)
GROUP BY FH.HOUR
ORDER BY FH.HOUR