WITH RECORDS AS (
    SELECT INS.ANIMAL_ID, INS.NAME, INS.DATETIME AS IN_DATE, OUTS.DATETIME AS OUT_DATE
    FROM ANIMAL_INS INS
    LEFT JOIN ANIMAL_OUTS OUTS
    ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
    ORDER BY IN_DATE
)

SELECT ANIMAL_ID, NAME
FROM RECORDS
WHERE IN_DATE >= OUT_DATE