SELECT FI.ID, NI.FISH_NAME, FI.LENGTH
FROM FISH_INFO FI
LEFT JOIN FISH_NAME_INFO NI
ON FI.FISH_TYPE = NI.FISH_TYPE
WHERE FI.LENGTH = (SELECT MAX(F.LENGTH) FROM FISH_INFO F
                  WHERE F.FISH_TYPE = FI.FISH_TYPE
                  GROUP BY F.FISH_TYPE)
ORDER BY FI.ID