SELECT F.ID, N.FISH_NAME, F.LENGTH
FROM FISH_INFO F
JOIN FISH_NAME_INFO N
ON N.FISH_TYPE = F.FISH_TYPE
WHERE F.LENGTH = (SELECT MAX(FI.LENGTH)
                 FROM FISH_INFO FI
                 WHERE FI.FISH_TYPE = F.FISH_TYPE)
ORDER BY F.ID asc